CREATE TABLE IF NOT EXISTS usuario(
id BIGINT(20) AUTO_INCREMENT NOT NULL,
login VARCHAR(255) NOT NULL,
senha VARCHAR(255) NOT NULL,
PRIMARY KEY (id)
);

INSERT INTO usuario (login, senha) VALUES ('alexandre', 'teste1');